export enum REVALIDATE {
  FETCH_SEARCH_FOODS = "FETCH_SEARCH_FOODS",
  FETCH_FIND_ONE_FOOD = "FETCH_FIND_ONE_FOOD",
  FETCH_ACTIVE_CATEGORIES = "FETCH_ACTIVE_CATEGORIES",
  FETCH_FIND_MANY_FAVORITES = "FETCH_FIND_MANY_FAVORITES",
}
