export enum REVALIDATE {
  FETCH_SEARCH_PRODUCTS = "FETCH_SEARCH_PRODUCTS",
  FETCH_FIND_ONE_PRODUCT = "FETCH_FIND_ONE_PRODUCT",
  FETCH_ACTIVE_CATEGORIES = "FETCH_ACTIVE_CATEGORIES",
  FETCH_FIND_MANY_FAVORITES = "FETCH_FIND_MANY_FAVORITES",
}
